name: Trigger Stream Workflow
description: Dispatch stream.yml using GH_PAT secret

inputs:
  video_url:
    required: true
  start_time:
    required: true
  duration_seconds:
    required: true
  seamless:
    required: false

runs:
  using: "composite"
  steps:
    - name: Dispatch stream.yml
      shell: bash
      run: |
        set -e
        OWNER_REPO="${GITHUB_REPOSITORY}"
        PAYLOAD=$(jq -n --arg v "$INPUT_VIDEO_URL" --arg s "$INPUT_START_TIME" --arg d "$INPUT_DURATION_SECONDS" --arg sm "$INPUT_SEAMLESS" '{ref:"main", inputs:{video_url:$v,start_time:$s,duration_seconds:$d,seamless:$sm}}')
        curl -s -X POST           -H "Authorization: token $GH_PAT"           -H "Accept: application/vnd.github.v3+json"           https://api.github.com/repos/${OWNER_REPO}/actions/workflows/stream.yml/dispatches           -d "$PAYLOAD"
